<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SwagLabs</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b15ab304-de99-4330-ad99-fbdab1aa3471</testSuiteGuid>
   <testCaseLink>
      <guid>fcb3f7d7-fafc-4a6e-9ffc-2fe8609ae6b3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OpenBrowser</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>8006bf40-90ea-4969-8f57-9b5f61cc9ccf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>244a1fb6-fdfe-4271-ad1f-ba8307636ddd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfc1201c-108c-489b-b446-232990f1a5a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5a37222f-9e38-4b08-8cb3-371d8fd5f1e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verify home and products</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>[&quot;Sauce Labs Backpack&quot;, &quot;Sauce Labs Bike Light&quot;, &quot;Sauce Labs Bolt T-Shirt&quot;, &quot;Sauce Labs Fleece Jacket&quot;, &quot;Sauce Labs Onesie&quot;, &quot;Test.allTheThings() T-Shirt (Red)&quot;]</value>
         <variableId>456d9eee-bb7d-4238-b18f-ab670cc90148</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>[&quot;Test.allTheThings() T-Shirt (Red)&quot;, &quot;Sauce Labs Onesie&quot;, &quot;Sauce Labs Fleece Jacket&quot;, &quot;Sauce Labs Bolt T-Shirt&quot;, &quot;Sauce Labs Bike Light&quot;, &quot;Sauce Labs Backpack&quot;]</value>
         <variableId>dc4a9bf1-c5c6-46c7-bc2f-7d6b93bd9e13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afbe75bc-d8b2-41e4-bdac-7ec8c97a26d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7cae626-2ecf-4294-bc37-d2fbafadd2c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>[&quot;https://www.saucedemo.com/static/media/sauce-backpack-1200x1500.34e7aa42.jpg&quot;, &quot;https://www.saucedemo.com/static/media/bike-light-1200x1500.a0c9caae.jpg&quot;, &quot;https://www.saucedemo.com/static/media/bolt-shirt-1200x1500.c0dae290.jpg&quot;, &quot;https://www.saucedemo.com/static/media/sauce-pullover-1200x1500.439fc934.jpg&quot;, &quot;https://www.saucedemo.com/static/media/red-onesie-1200x1500.1b15e1fa.jpg&quot;, &quot;https://www.saucedemo.com/static/media/red-tatt-1200x1500.e32b4ef9.jpg&quot;]</value>
         <variableId>8ccbe8dc-b57a-45f4-9d32-bb0ece7d598a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91cb717a-9e00-442a-9b62-300fdc7cf36c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6aa6cda9-4de1-444a-8f71-acaf0a796e74</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>de690930-6a49-4b42-b1f1-824614e8feb3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BuyProduct</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06dfeff7-f67c-4717-89ad-e6bbf369585b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9bdf27a-59b6-4dc7-89a4-be22c0ed9a48</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ac82795-aebc-400b-9576-bdfea1f784cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a5bd7da-ac7f-4de5-bc60-6c42c66cc43d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3501c75f-60dc-4b43-90a9-e12f7ae46cf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>175932d8-9e98-42f5-abe6-449015e1ba10</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d4679241-a1a9-4371-a084-9f3f8da0fb00</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Logout</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>651ec46a-a680-40d7-9234-b9b64430f431</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;locked_out_user&quot;</value>
         <variableId>244a1fb6-fdfe-4271-ad1f-ba8307636ddd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfc1201c-108c-489b-b446-232990f1a5a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3593cb68-1bf1-4583-97e2-cabb167801f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;problem_user&quot;</value>
         <variableId>244a1fb6-fdfe-4271-ad1f-ba8307636ddd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfc1201c-108c-489b-b446-232990f1a5a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4d44729b-4451-453e-830f-63d38fd8afab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verify home and products</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>456d9eee-bb7d-4238-b18f-ab670cc90148</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc4a9bf1-c5c6-46c7-bc2f-7d6b93bd9e13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>false</value>
         <variableId>afbe75bc-d8b2-41e4-bdac-7ec8c97a26d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7cae626-2ecf-4294-bc37-d2fbafadd2c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>[&quot;https://www.saucedemo.com/static/media/sauce-backpack-1200x1500.34e7aa42.jpg&quot;, &quot;https://www.saucedemo.com/static/media/bike-light-1200x1500.a0c9caae.jpg&quot;, &quot;https://www.saucedemo.com/static/media/bolt-shirt-1200x1500.c0dae290.jpg&quot;, &quot;https://www.saucedemo.com/static/media/sauce-pullover-1200x1500.439fc934.jpg&quot;, &quot;https://www.saucedemo.com/static/media/red-onesie-1200x1500.1b15e1fa.jpg&quot;, &quot;https://www.saucedemo.com/static/media/red-tatt-1200x1500.e32b4ef9.jpg&quot;]</value>
         <variableId>8ccbe8dc-b57a-45f4-9d32-bb0ece7d598a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>false</value>
         <variableId>91cb717a-9e00-442a-9b62-300fdc7cf36c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
